# Generated by Django 3.0.2 on 2020-01-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200122_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='borrewer',
            new_name='borrower',
        ),
    ]
